spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
mybatis:
  type-aliases-package: com.maplesong.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

---

#dev
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maplesong?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: ssw200212

logging:
  level:
    root: info
    com.maplesong: debug
  file:
    name: log/blog-dev.log
server:
  port: 80
---

#pro
spring:
  profiles: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maplesong?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: ssw200212

logging:
  level:
    root: warn
    com.maplesong: info
  file:
    name: log/blog-pro.log

server:
  port: 8888
